"""added is_protected to the user

Revision ID: 74f7d20f1d3c
Revises: 944d8ead331a
Create Date: 2026-07-28 17:58:02.039943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f7d20f1d3c'
down_revision = '944d8ead331a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_protected', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_protected')

    # ### end Alembic commands ###
